# Route qui affiche le formulaire de saisie du code 2FA (TOTP, email, etc.)
2fa_login:
  path: /2fa
  controller: "scheb_two_factor.form_controller:form"

# Route qui traite et vérifie le code 2FA soumis par l'utilisateur
2fa_login_check:
  path: /2fa_check