# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    # response:
    #     headers:
    #         content_security_policy:
    #             default-src: "'self'"
    #             script-src: "'self'"
    #             style-src: "'self' 'unsafe-inline'"
    #             img-src: "'self' data:"
    #             font-src: "'self' data:"
    #             connect-src: "'self' api.example.com"
    #             object-src: "'none'"
    #             frame-ancestors: "'none'"

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
