scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
        - Lexik\Bundle\JWTAuthenticationBundle\Security\Authentication\Token\JWTUserToken
    
    totp:
        enabled: true
        server_name: 'Mon App'
        issuer: 'Mon App'
        
    google:
        enabled: true
        server_name: 'Mon App'
        issuer: 'Mon App'
        
    email:
        enabled: true
        sender_email: 'noreply@monapp.com'
        sender_name: 'Mon App'
        digits: 6
        template: 'security/2fa_email.html.twig'