when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        make_factory:
            default_namespace: 'App\\Factory'
            default_path: '%kernel.project_dir%/src/Factory'

when@test: *dev
